config/routes.rb
Rails.application.routes.draw do
  resources :user_groups
  resources :tasks do
    resources :comments
  end
  resources :projects
  resources :groups

  resources :notifications, only: [:index]
  
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  get 'change_role', to: 'roles#change_role'
  match 'change_role', to: 'roles#update_role', via: [:post, :patch]

  root "home#index"

  resources :users do
    get 'logout', on: :member, to: 'users#logout'
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :task
    belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @task = Task.find(params[:task_id])
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new
    @task = Task.find(params[:task_id])
    @comment.task_id = @task.id 
    @comment.content = params[:content]
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to task_url(@task), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    if @comment.update("content": params[:comment][:content])
      head :no_content
    else
      head :unprocessable_entity
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    if @comment.destroy
      head :no_content
    else
      head :unprocessable_entity
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.fetch(:comment, {}).permit(:content, :task_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
</div>

app/views/comments/_form.html.erb
<style>

  .card {
    margin-right: 5px;
    margin-left: 5px;
    margin-bottom: 10px;
  }

  .comment-card {
    background-color: #f6efef;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }
</style>

<head>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
</head>

<body>
  <div id="top-page">

    <div id="wrapper">
      <div class="container my-5">
        <div class="card">
          <div class="card-body align-items-center justify-content">
            <div>
            <h1>Crear un comentario</h1>
            </div>

            <%= form_with(model: comment, url: task_comments_path(@task.id)) do |form| %>
                <% if comment.errors.any? %>
                  <div style="color: red">
                    <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

                    <ul>
                      <% comment.errors.each do |error| %>
                        <li><%= error.full_message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>

                <p>Recuerda que este comentario será visible para todos los integrantes del grupo</p>
                <p class = "text-muted">Comentando en: "<%= @task.name %>"</p>

                <div class="form-group">
                  <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="content" placeholder = "Escribe tu comentario..."></textarea>
                </div>

                <div class="text-center mt-4">
                  <%= form.submit 'Publicar Comentario', class: 'btn btn-primary' %>
                </div>
                <div>
                  <button class="btn btn-secondary" style = "margin-bottom: 10px;" onclick="history.back()" type = "button">Back</button>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</body>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<div style="margin-top: 80px;">
    <%= render "form", comment: @comment %>

    <br>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>