config/routes.rb
Rails.application.routes.draw do
  resources :user_groups
  resources :tasks do
    resources :comments
  end
  resources :projects
  resources :groups

  resources :notifications, only: [:index]
  
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  get 'change_role', to: 'roles#change_role'
  match 'change_role', to: 'roles#update_role', via: [:post, :patch]

  root "home#index"

  resources :users do
    get 'logout', on: :member, to: 'users#logout'
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/task.rb
class Task < ApplicationRecord

    belongs_to :user
    has_many :comments
    belongs_to :group

    enum status: {
        pending: 0,
        finished: 1
    }

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.where(group_id: current_user.groups.pluck(:id))
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    @group = Group.find(@task.group_id)
    @comments = @task.comments
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @my_groups = current_user.groups
  end

  # GET /tasks/1/edit
  def edit
    @my_groups = current_user.groups
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    @task.start_date = Date.today
    
    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to "/tasks", notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.fetch(:task, {}).permit(:name, :description, :status, :end_date, :progress, :group_id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
</div>

app/views/tasks/edit.html.erb
<style>

.field {
  display: flex;
  align-items: center;
  margin-bottom: 20px;
}

.field label {
  flex: 0 0 auto; 
  margin-right: 10px;
}

.field select, .field input, .field textarea {
  flex: 1;
  width: auto;
  max-width: 700px;
  min-height: 30px;
}

.container {
  display: flex;
  justify-content: center;
  margin-top: 20px;
  align-items: center;
  height: auto;
  width: auto;
}

.card {
  height: auto;
  width: 800px;
}

.actions {
  margin-top: 10px;
}

</style>

<h2 style="margin-left: 260px; margin-top: 20px ">Editar tarea</h2>

<div class="container">
  <div class="card">
    <div class="card-body"> 
      <%= form_with(model: @task, url: task_path(@task), method: :patch, local: true) do |form| %>
        <div class="field">
          <%= form.label :name %>
          <%= form.text_field :name %>
        </div>

        <div class="field">
          <%= form.label :description %>
          <%= form.text_area :description %>
        </div>

        <div class="field">
          <%= form.label :status %>
          <%= form.select :status, Task.statuses.keys %>
        </div>

        <div class="field">
          <%= form.label :end_date %>
          <%= form.date_field :end_date, min: Date.today %>
        </div>

        <div class="field">
          <%= form.label :progress %>
          <%= form.number_field :progress, max: 100 %>
        </div>

        <div class="field">
          <%= form.label :group_id %>
          <%= form.collection_select(:group_id, @my_groups, :id, :name, { include_blank: "Select a group" }) %>
        </div>

        <hr>

        <div class="actions">
          <%= form.submit class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<br>

<div>
  <%= link_to "Mostrar esta tarea", @task %> |
  <%= link_to "Volver a las tareas", tasks_path %>
</div>

app/views/tasks/index.html.erb
<div style= "margin-left: 40px; margin-top: 30px;">

  <div>
    <h4>Tareas</h4>
    <hr>
    <div class="card-container">
      <% @tasks.each do |task| %>
        <div class="card mb-3" style="width: 190vh;">
          <div class="card-body">
            <h5 class="card-title"><b><%= task.name %></b></h5>
            <p class="card-text" style="color: #696969"><%= task.start_date %> | <%= task.end_date %></p>
            <p class="card-text">Creado/a por: <%= task.user.name %></p>
            <p class="card-text">Descripción: <%= task.description %></p>
            <div class="progress">
              <div class="progress-bar" style="width: <%= task.progress %>%;" aria-valuenow="<%= task.progress %>" aria-valuemin="0" aria-valuemax="100"><%= task.progress %>%</div>
            </div>
            <div style="display: flex;">
              <a href=<%= edit_task_url(task) %> class= "btn btn-primary" style="margin-top: 10px;">Editar</a>
              <% if task.user.id == current_user.id %>
                <%= button_to "Eliminar", task, class: "btn btn-danger", style: "margin-top: 10px;", method: :delete, data: {turbo_method: :delete, turbo_confirm: '¿Estás seguro que quieres eliminar?'}%>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/tasks/new.html.erb
<style>

.field {
  display: flex;
  align-items: center;
  margin-bottom: 20px;
}

.field label {
  flex: 0 0 auto; 
  margin-right: 10px;
}

.field select, .field input, .field textarea {
  flex: 1;
  width: auto;
  max-width: 700px;
  min-height: 30px;
}

.container {
  display: flex;
  justify-content: center;
  margin-top: 20px;
  align-items: center;
  height: auto;
  width: auto;
}

.card {
  height: auto;
  width: 800px;
}

.actions {
  margin-top: 10px;
}

</style>

<h2 style="margin-left: 260px; margin-top: 20px ">New task</h2>

<div class="container">
  <div class="card">
    <div class="card-body"> 
      <%= form_with(model: @task, url: tasks_path, local: true) do |form| %>
        <div class="field">
          <%= form.label :name %>
          <%= form.text_field :name %>
        </div>

        <div class="field">
          <%= form.label :description %>
          <%= form.text_area :description %>
        </div>

        <div class="field">
          <%= form.label :status %>
          <%= form.select :status, Task.statuses.keys %>
        </div>


        <div class="field">
          <%= form.label :end_date %>
          <%= form.date_field :end_date, min: Date.today %>
        </div>

        <div class="field">
          <%= form.label :progress %>
          <%= form.number_field :progress, max: 100 %>
        </div>

        <div class="field">
          <%= form.label :group_id %>
          <%= form.collection_select(:group_id, @my_groups, :id, :name, { include_blank: "Select a group" }) %>
        </div>

        <hr>

        <div class="actions">
          <%= form.submit class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<br>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/show.html.erb
<style>
.card {
    margin-right: 5px;
    margin-left: 5px;
    margin-bottom: 10px;
  }

  .comment-cards {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 20px;
  }

  .comment-card {
    background-color: #f6efef;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    position: relative;
  }

  .comment-title {
    font-size: 18px;
    font-weight: bold;
    margin-bottom: 10px;
  }

  .no-decorator {
    text-decoration: none;
  }

  .no-decorator:hover {
    text-decoration: none;
    cursor: pointer;
  }

  .btn-reopen {
    position: absolute;
    top: 0;
    right: 0;
    margin-top: 10px;
    margin-right: 10px; 
  }

  .no-comment {
    background-color: transparent;
  }

  .comment-details {
    margin-bottom: 5px;
  }

  .icon {
    margin-bottom: 6px;
  }

    .comment-header {
      display: flex;
      align-items: center;
      margin-left: 15px;
      position: relative; 
  }

  .comment-header .add-comment {
      position: absolute;
      top: 0;
      right: 0;
      margin-right: 10px;
  }

  .comment-card .comments-icons {
    display: flex; 
    position: absolute; 
    right: 0; 
    top: 0;
    margin-top: 10px;
    margin-right: 10px;
  }

  .comment-card .comments-icons > * {
    margin-right: 10px;
}

.comments-icons i.edit-button:hover {
  color: blue;
}

.comments-icons i.delete-button:hover {
  color: red;
}

</style>

<div class="container" style="margin-top: 60px;">
<h2><%= @task.name %></h2>
  <div class="card">
    <div class="card-body">
      <p><strong>Nombre:</strong> <%= @task.name %></p>
      <p><strong>Creado/a por: </strong><%= User.find(@task.user_id).name %></p>
      <p><strong>Descripción:</strong> <%= @task.description %></p>
      <p><strong>Estado:</strong> <%= @task.status %></p>
      <p><strong>Fecha de finalización:</strong> <%= @task.end_date %></p>
      <p><strong>Progreso:</strong> <%= @task.progress %>%</p>
      <p><strong>Grupo:</strong> <%= @group.name %></p>
    </div>
  </div>
</div>

<br>

<div style= "margin-left: 15px ; ">
  <%= link_to "Editar esta tarea", edit_task_path(@task), class: "btn btn-primary"%> |
  <%= link_to "Volver a las tareas", tasks_path, class: "btn btn-secundary" %>
</div>

<hr>

<div>

  <div class="comment-header">
    <i class="bi bi-chat-left-dots" style="margin-bottom: 6px; margin-right: 6px"></i>
    <h2>Comentarios</h2>
    <% if current_user.groups.include?(@task.group) %>
      <a href="<%= new_task_comment_path(@task) %>" class="btn btn-primary add-comment" style="position: absolute; right: 0; top: 0; margin-right: 10px;">Dejar un comentario <i class="bi bi-plus"></i></a>  
    <% end %>            
  </div>



  <div class="comment-cards">
    <% if @comments.any? %>
      <% @comments.each do |comment| %>
        <div class="comment-card">
          <div class="comments-icons">
            <i class="bi bi-pencil-square edit-button" id="edit-button" data-comment-id="<%= comment.id %>" data-task-id="<%= @task.id %>"></i>
            <i class="bi bi-trash delete-button" data-comment-id="<%= comment.id %>" data-task-id="<%= @task.id %>"></i>
          </div>
          <div style="display: flex;">
            <h4 class="comment-title"><%= comment.user.name %> <%= comment.user.last_name %></h4>
          </div>
          <p class="ticket-details text-muted"> <%= comment.created_at %></p>
          <p class="ticket-details" id="comment-content"> <%= comment.content %></p>
        </div>
      <% end %>
    <% else %>
      <div class="comment-card no-comment">
        <div style="display: flex;">
          <h4 class="comment-title">No hay comentarios en esta tarea</h4>
        </div>
        <i class='fas fa-comment-slash' style='font-size:24px'></i>
      </div>
    <% end %>
  </div>

</div>


<script>

  document.addEventListener("DOMContentLoaded", function () {
        const editButtons = document.querySelectorAll(".edit-button");

        editButtons.forEach(function (button) {
            button.addEventListener("click", function () {
                const commentId = button.getAttribute("data-comment-id");
                const taskId = button.getAttribute("data-task-id");

                const commentContent = document.getElementById("comment-content");

                const currentContent = commentContent.textContent;
                const editForm = document.createElement("form");

                editForm.style.display = "flex";
                editForm.style.flexDirection = "column";

                const textarea = document.createElement("textarea");
                const saveButton = document.createElement("button");
                const cancelButton = document.createElement("button");

                saveButton.style.marginTop = "10px";
                cancelButton.style.marginTop = "10px";

                saveButton.classList.add("btn");
                saveButton.classList.add("btn-info");
                cancelButton.classList.add("btn");
                cancelButton.classList.add("btn-danger");

                textarea.value = currentContent;
                saveButton.textContent = "Guardar";
                cancelButton.textContent = "Cancelar";

                saveButton.addEventListener("click", function () {
                    const newContent = textarea.value;

                    fetch(`${taskId}/comments/${commentId}`, {
                      method: "PUT",
                      headers: {
                          "Content-Type": "application/json",
                          "X-CSRF-Token": "<%= form_authenticity_token %>"
                      },
                      body: JSON.stringify({ comment: { content: newContent } })
                  })
                  .then(response => {
                      if (response.ok) {
                          alert("Comentario actualizado con éxito");
                          commentContent.textContent = newContent;
                      } else {
                          alert("No se pudo actualizar el comentario");
                      }
                  })
                  .catch(error => {
                      console.error("Error:", error);
                  });
                    commentContent.removeChild(editForm);
                });

                cancelButton.addEventListener("click", function () {
                    commentContent.textContent = currentContent;

                    commentContent.removeChild(editForm);
                });

                editForm.appendChild(textarea);
                editForm.appendChild(saveButton);
                editForm.appendChild(cancelButton);

                commentContent.innerHTML = "";
                commentContent.appendChild(editForm);
            });
        });
    });

    document.addEventListener("DOMContentLoaded", function () {
        const deleteButtons = document.querySelectorAll(".delete-button");

        deleteButtons.forEach(function (button) {
            button.addEventListener("click", function () {
                const commentId = button.getAttribute("data-comment-id");
                const taskId = button.getAttribute("data-task-id");
                const confirmation = confirm("¿Seguro que quieres eliminar el comentario?");

                if (confirmation) {
                    fetch(`${taskId}/comments/${commentId}`, {
                        method: "DELETE",
                        headers: {
                            "Content-Type": "application/json",
                            "X-CSRF-Token": "<%= form_authenticity_token %>"
                        }
                    })
                        .then(response => {
                            if (response.ok) {
                                alert("Comentario eliminado.");
                                window.location.reload();
                            } else {
                                alert("No se pudo eliminar el comentario.");
                            }
                        })
                        .catch(error => {
                            console.error("Error:", error);
                        });
                }
            });
        });
    });
</script>