config/routes.rb
Rails.application.routes.draw do
  resources :user_groups
  resources :tasks do
    resources :comments
  end
  resources :projects
  resources :groups

  resources :notifications, only: [:index]
  
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  get 'change_role', to: 'roles#change_role'
  match 'change_role', to: 'roles#update_role', via: [:post, :patch]

  root "home#index"

  resources :users do
    get 'logout', on: :member, to: 'users#logout'
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    enum role: {
        Desarrollador: 0,
        Supervisor: 1,
        Gerente: 2
    }
    
  has_many :user_groups
  has_many :groups, through: :user_groups
  has_many :tasks
  has_many :comments

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show_current
    @user = User.find(current_user.id)
  end

  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end
  
  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def logout
    sign_out(@user)
    redirect_to root_path, notice: 'Logged out successfully.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :last_name, :telefono, :email, :role)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
</div>

app/views/users/edit.html.erb
<h1 style="color: green; text-align: center;">Editing user</h1><br><br><br><br>
<div style="display: flex; justify-content: center; align-items: center; height: 50vh;">
  <div style="background-color: #f7f7f7; border: 1px solid #ddd; padding: 20px; max-width: 400px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); border-radius: 5px;">
      <%= form_for(@user) do |f| %>
        <div class="field">
          <%= f.label :name %>:<br>
          <%= f.text_field :name %>
        </div>
      
        <div class="field">
          <%= f.label :last_name %>:<br>
          <%= f.text_field :last_name %>
        </div>
      
        <div class="field">
          <%= f.label :email %>:<br>
          <%= f.text_field :email %>
        </div>
      
        <div class="field">
          <%= f.label :telephone %>:<br>
          <%= f.text_field :telephone %>
        </div>
      
        <div class="field">
          <%= f.label :role %>:<br>
          <%= f.text_field :role %>
        </div>

        <br>
        <div style=" text-align: center;">
        <div class="actions">
          <%= f.submit "Actualizar datos", class: "btn btn-success", style: "text-decoration: none; margin: 5px; padding: 10px 20px; border-radius: 5px; font-weight: bold; display: inline-block; transition: background-color 0.3s, color 0.3s;" %>
        </div>
      <% end %>

    
    <div style="margin-top: 20px; text-align: center;">
      <%= link_to "Volver al perfil", @user, class: "btn btn-primary", style: "text-decoration: none; margin: 5px; padding: 10px 20px; border: 2px solid #007bff; background-color: #007bff; color: #fff; border-radius: 5px; font-weight: bold; display: inline-block; transition: background-color 0.3s, color 0.3s;" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<div style="background-color: #f7f7f7; border: 1px solid #ddd; padding: 20px; text-align: center; max-width: 400px; margin: 0 auto; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); border-radius: 5px;">
  <h2>User Profile</h2>

  <div style="margin-top: 20px;">
    <p><strong>Name:</strong> <%= @user.name %></p>
    <p><strong>Last Name:</strong> <%= @user.last_name %></p>
    <p><strong>Email:</strong> <%= @user.email %></p>
    <p><strong>Telephone:</strong> <%= @user.telephone %></p>
    <p><strong>Role:</strong> <%= @user.role %></p>
  </div>

  <div style="margin-top: 20px;">
    <%= link_to "Editar datos", edit_user_path(@user), class: "btn btn-primary", style: "text-decoration: none; margin: 5px; padding: 10px 20px; border: 2px solid #007bff; background-color: #007bff; color: #fff; border-radius: 5px; font-weight: bold; display: inline-block; transition: background-color 0.3s, color 0.3s;" %>

    <%= button_to "Eliminar este usuario", @user, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger", style: "text-decoration: none; margin: 5px; padding: 10px 20px; border: 2px solid #dc3545; background-color: #dc3545; color: #fff; border-radius: 5px; font-weight: bold; display: inline-block; transition: background-color 0.3s, color 0.3s;" %>

    <% if current_user && current_user.id == @user.id %>
        <%= link_to "Logout", logout_user_path(@user), method: :get, class: "btn btn-secondary", style: "text-decoration: none; margin: 5px; padding: 10px 20px; border: 2px solid #6c757d; background-color: #6c757d; color: #fff; border-radius: 5px; font-weight: bold; display: inline-block; transition: background-color 0.3s, color 0.3s;" %>
    <% end %>

  </div>
</div>