config/routes.rb
Rails.application.routes.draw do
  resources :user_groups
  resources :tasks do
    resources :comments
  end
  resources :projects
  resources :groups

  resources :notifications, only: [:index]
  
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  get 'change_role', to: 'roles#change_role'
  match 'change_role', to: 'roles#update_role', via: [:post, :patch]

  root "home#index"

  resources :users do
    get 'logout', on: :member, to: 'users#logout'
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html>
<head>
    <style>
        /* Styles for the navigation bar */
        .navbar {
            background-color: #eff2d8; /* Yellow background */
            color: #000; /* Black font color */
            display: flex;
            justify-content: space-between;
            padding: 20px; /* Increased padding for a bigger navbar */
        }

        /* Styles for the left side of the navigation bar */
        .navbar-left {
            display: flex;
        }

        .navbar-left a {
            text-decoration: none;
            color: #000; /* Black font color */
            padding: 10px;
            font-size: 16px; /* Increase the font size */
        }

        /* Styles for the right side of the navigation bar */
        .navbar-right {
            display: flex;
            align-items: center; /* Center vertically within the navbar */
        }

        .navbar-right .user-info {
            text-align: right;
            padding: 10px;
            font-size: 16px; /* Increase the font size */
        }

        .user-icon {
            font-size: 48px; 
            color: #484848;
            margin-bottom: 7px;
        }

        .profile-button {
            color: white; /* Button text color */
            padding: 5px 10px; /* Button padding */
            border: none; /* No button border */
            border-radius: 5px; /* Rounded button corners */
            cursor: pointer; /* Add cursor on hover */
        }
    </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <div class="navbar">
        <div class="navbar-left">
            <%= link_to 'Inicio', root_path, class: 'nav-link active', style: "color: black; font-weight: 500; font-size: 20;" %>
            <%= link_to 'Tablero', tasks_path, class: 'nav-link active', style: "color: black; font-weight: 500; font-size: 20;" %>
            <%= link_to 'Bandeja de entrada', "/notifications", class: 'nav-link active', style: "color: black; font-weight: 500; font-size: 20;" %>
            <% if current_user.role == "Supervisor" %>
              <%= link_to 'Cambiar rol de usuarios', change_role_path, class: 'nav-link', style: "color: black; font-weight: 500; font-size: 20;" %>
            <% end %>
        </div>
        <div class="navbar-right">
          <% if current_user %>
            <div class="user-info">
              <span style="color: black; font-weight: 500; font-size: 16px;">
                <%= "#{current_user.name} #{current_user.last_name}" %>
              </span>
              <br>
              <span style="color: grey; font-size: 80%;">
                <%= "#{current_user.role}" %>
              </span>
            </div>
            <%= link_to user_path(current_user) do %>
              <i class="user-icon fas fa-user-circle"></i>
            <% end %>
          <% end %>
        </div>
    </div>
</body>
</html>

app/views/layouts/application.html.erb
<style>

.navbar-container {
  position: relative;
}

.new_task_button {
  position: absolute;
  top: 10px; 
  right: 10px;
  margin-top: 20px;
  margin-right: 20px;
  margin-bottom: 20px;
}


</style>

<!DOCTYPE html>
<html>
  <head>
    <title>TechSolver</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style= "background: #f9f9f9; font-family: roboto, sans-serif;">
    <% if user_signed_in? %>
      <%= render 'layouts/navbar' %>
      <div class="navbar-container">
        <a href=<%= new_task_path %> class="btn btn-info new_task_button">New Task</a>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>